// Controlled vocabulary for Bangalore localities.
//
// Mirror of FE: ApnaRent/src/lib/bangaloreLocalities.ts. Names match Google
// Places address_components long_name (sublocality_level_1). The list is used:
//   - as a Claude tool-use enum, forcing NL-search locality extraction to
//     return a value the FE dropdown actually contains, and
//   - by canonicalizeLocality() to coerce regex-fallback and synonym variants
//     to the canonical spelling.
//
// Keep in sync with the FE file — when editing one, edit both.
// Last refreshed 2026-05-20.

export const BANGALORE_LOCALITIES = [
  "Adigara Kallahalli",
  "Adugodi",
  "Agrahara Layout",
  "Agram",
  "Akshayanagar",
  "Andrahalli",
  "Anjanapura",
  "Anjanapura Township",
  "Annapurneshwari Nagar",
  "Arebannimangala",
  "Arekere",
  "Arenur",
  "Armane Nagar",
  "Ashok Nagar",
  "Avalahalli",
  "B.Marenahalli",
  "BEML Cooperative Society Layout",
  "BTM Layout",
  "Babusapalya",
  "Bagalagunte",
  "Bagalur",
  "Banashankari",
  "Banaswadi",
  "Bande Kodigehalli",
  "Bannerghatta Road",
  "Basavanagudi",
  "Basaveshwaranagar",
  "Battarahalli",
  "Begur",
  "Bellahalli",
  "Bellandur",
  "Bennigana Halli",
  "Benson Town",
  "Bethanagere",
  "Bettadasanapura",
  "Bharat Nagar",
  "Bhoganhalli",
  "Bidare Agraha",
  "Bilekahalli",
  "Bilijaji",
  "Billapura",
  "Binnipete",
  "Bommanahalli",
  "Bommasandra",
  "Brookefield",
  "Byadarahalli",
  "Byatarayanapura",
  "C V Raman Nagar",
  "Carmelaram",
  "Challaghatta",
  "Chamrajpet",
  "Chandapura",
  "Chandra Layout",
  "Channasandra",
  "Cheemasandra",
  "Chikkabanavara",
  "Chikkabidarakallu",
  "Chikkakannalli",
  "Chikkalasandra",
  "Chikkanagamangala",
  "Chinthalamadivala",
  "Chokkasandra",
  "Choodasandra",
  "Choudadenahalli",
  "Cleveland Town",
  "Cooke Town",
  "Cox Town",
  "Cunningham Road",
  "Dasanayakanahalli",
  "Devanahalli",
  "Devara Jeevanahalli",
  "Devasandra Layout",
  "Doddabidarakallu",
  "Doddabommasandra",
  "Doddakannelli",
  "Doddanekkundi",
  "Doddenahalli",
  "Domlur",
  "Dommasandra",
  "Dooravani Nagar",
  "Electronic City",
  "Fraser Town",
  "Gandhi Nagar",
  "Gantiganahalli",
  "Garvebhavi Palya",
  "Gattahalli",
  "Gnana Bharathi",
  "Gopalapura",
  "Gopasandra",
  "Gottigere",
  "Govindarajanagar",
  "Guddadahalli",
  "Gulimangala",
  "Gummanahalli",
  "Gunjur Palya",
  "Guttahalli",
  "HBR Layout",
  "HRBR Layout",
  "HSR Layout",
  "Handenahalli",
  "Harlur",
  "Hebbagodi",
  "Hebbal",
  "Hebbal Kempapura",
  "Heelalige",
  "Hegganahalli",
  "Hennagara",
  "Hennur",
  "Hennur Gardens",
  "Hesargatta",
  "Hombegowda Nagar",
  "Hoodi",
  "Horamavu",
  "Hosa Road",
  "Hosahalli",
  "Hosakerehalli",
  "Hosur Road",
  "Hulimavu",
  "Hunasamaranahalli",
  "Hunasemaradapalya",
  "Huvinayakanahalli",
  "ISRO Layout",
  "ITPL",
  "Indiranagar",
  "Ittangur",
  "Ivar Kandapura",
  "J. P. Nagar",
  "J.C.Nagar",
  "Jakkur",
  "Jalahalli",
  "Jalahalli West",
  "Jayanagar",
  "Jnana Ganga Nagar",
  "Jyothi Nagar",
  "Kachamaranahalli",
  "Kadugodi",
  "Kadusonnapanahalli",
  "Kaggadasapura",
  "Kaikondrahalli",
  "Kalasipalya",
  "Kalena Agrahara",
  "Kalkere",
  "Kalyan Nagar",
  "Kamala Nagar",
  "Kammanahalli",
  "Kammavari Pete",
  "Kanakapura Road",
  "Kannuru",
  "Kanva Garden City",
  "Kasavanahalli",
  "Kasghattapura",
  "Kasturi Nagar",
  "Kattigenahalli",
  "Kaval Bairasandra",
  "Kengeri",
  "Kengeri Satellite Town",
  "Khajisonnanahalli",
  "Kithaganur Colony",
  "Kodihalli",
  "Kodipalya",
  "Kogilu",
  "Kolipura",
  "Kommasandra",
  "Konanakunte",
  "Koppa",
  "Koramangala",
  "Kothanur",
  "Krishnarajapuram",
  "Kumaraswamy Layout",
  "Kundalahalli",
  "Lakshmisagara",
  "Lavelle Road",
  "Lingarajapuram",
  "MG Road",
  "Madanayakahalli",
  "Madhav Nagar",
  "Magadi Road",
  "Mahadeva Kodigehalli",
  "Mahadevapura",
  "Mahalakshmi Layout",
  "Mailasandra",
  "Mallathahalli",
  "Malle Nalsandra",
  "Malleshwaram",
  "Maralakunte",
  "Maranayakanahalli",
  "Marathahalli",
  "Margondanahalli",
  "Mathikere",
  "Mavalli",
  "Medahalli",
  "Meesaganahalli",
  "Mico Layout",
  "Munnekollal",
  "Muthanallur",
  "Mylappanahalli",
  "Mysore Road",
  "Nagarbhavi",
  "Nagavara",
  "Nandini Layout",
  "Narayanaghatta",
  "Nayanda Halli",
  "Neelasandra",
  "New Thippasandra",
  "Nisarga Layout",
  "Nrithyagram",
  "Old Airport Road",
  "Omkar Nagar",
  "Padmanabhanagar",
  "Panduranga Nagar",
  "Parappana Agrahara",
  "Pavamanapura",
  "Peenya",
  "Pillaganahalli",
  "Pillahalli",
  "Pulikeshi Nagar",
  "RK Hegde Nagar",
  "RMV Extension",
  "RT Nagar",
  "Rajajinagar",
  "Rajarajeshwari Nagar",
  "Ramamurthy Nagar",
  "Ramanahalli",
  "Rampalya",
  "Rayasandra",
  "Razack Palya",
  "Richards Town",
  "Richmond Town",
  "S.G. Palya",
  "SMV Layout",
  "Sadashivanagar",
  "Sahakar Nagar",
  "Sanjayanagara",
  "Sanjeevini Nagar",
  "Sannatammanahalli",
  "Sarjapur Road",
  "Sarjapura",
  "Sarvagnanagar",
  "Seshadripuram",
  "Shanti Nagar",
  "Shivaji Nagar",
  "Singasandra",
  "Singena Agrahara",
  "Sivanchetti Gardens",
  "Srinivasa Nagar",
  "Srinivaspur",
  "Srinivaspura",
  "Srirampura",
  "Subramanyapura",
  "Suncity Layout",
  "Sunkadakatte",
  "Talaghattapura",
  "Thanisandra",
  "Thigalarapalya",
  "Thippasandra",
  "Thirumalashettyhally",
  "Tirumalapura",
  "Totagere",
  "Ullal Uppanagar",
  "Ulsoor",
  "Uttarahalli",
  "Vabasandra",
  "Vaderahalli",
  "Valageripura",
  "Varadharaja Nagar",
  "Varthur",
  "Vasanth Nagar",
  "Vibhutipura",
  "Victoria Layout",
  "Vidyamanya Nagar",
  "Vidyanagar",
  "Vidyaranyapura",
  "Vignana Kendra",
  "Vijayanagar",
  "Visthar",
  "Vittasandra",
  "Vivekanandanagar",
  "Whitefield",
  "Williams Town",
  "Wilson Garden",
  "Yadiyuru",
  "Yarandahalli",
  "Yelahanka",
  "Yelahanka New Town",
  "Yeswanthpur",
];

// Common colloquial / abbreviated names → canonical entries above.
// Keep narrow and well-attested; extend as users surface more variants.
const SYNONYMS = {
  "kr puram": "Krishnarajapuram",
  "k r puram": "Krishnarajapuram",
  "krishnaraja puram": "Krishnarajapuram",
  krishnarajpuram: "Krishnarajapuram",
  hsr: "HSR Layout",
  btm: "BTM Layout",
  "jp nagar": "J. P. Nagar",
  "j p nagar": "J. P. Nagar",
  "j.p. nagar": "J. P. Nagar",
  "jc nagar": "J.C.Nagar",
  "j c nagar": "J.C.Nagar",
  "rt nagar": "RT Nagar",
  rmv: "RMV Extension",
  "mg road": "MG Road",
  "m g road": "MG Road",
  "cv raman nagar": "C V Raman Nagar",
  "c v raman nagar": "C V Raman Nagar",
  doddanakundi: "Doddanekkundi",
  challagata: "Challaghatta",
  challaghata: "Challaghatta",
  bengaluru: null, // city, not locality — caller treats as null locality
  bangalore: null,
};

const CANONICAL_BY_LOWER = new Map(
  BANGALORE_LOCALITIES.map((l) => [l.toLowerCase(), l]),
);

function stripPunctuation(s) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

const CANONICAL_BY_STRIPPED = new Map(
  BANGALORE_LOCALITIES.map((l) => [stripPunctuation(l), l]),
);

// Normalize a user-typed or LLM-extracted locality string to a canonical
// FE-list entry. Returns null if no confident match — callers fall back to
// dropping the locality filter (or relying on city/centroid alone).
export function canonicalizeLocality(text) {
  if (!text || typeof text !== "string") return null;
  const norm = text.trim().toLowerCase();
  if (!norm) return null;

  if (CANONICAL_BY_LOWER.has(norm)) return CANONICAL_BY_LOWER.get(norm);

  if (norm in SYNONYMS) return SYNONYMS[norm];

  const stripped = stripPunctuation(norm);
  if (CANONICAL_BY_STRIPPED.has(stripped))
    return CANONICAL_BY_STRIPPED.get(stripped);

  return null;
}
